Repository chipi-hub-team/chipi-hub, pull requests merged in 2024-12, with the labels that each got.

#22 chore: New github workflows for Continuous integration
  .github/workflows/codacy.yml
  .github/workflows/commits.yml
  .github/workflows/deloyment_on_render.yml
  .github/workflows/format.yml
  .github/workflows/tests.yml
  .mailmap
Labels: configuration

#25 Docker renamed
  .env.docker.example
  .github/workflows/deloyment_on_render.yml
  .mailmap
  app/modules/fakenodo/routes.py
  app/modules/zenodo/services.py
  docker/docker-compose.yml
Labels: configuration

#30 fix: Download all datasets button missed
  app/templates/base_template.html
Labels: bug

#28 Feat/stagging area
  .github/workflows/tests.yml
  app/modules/dataset/models.py
  app/modules/dataset/repositories.py
  app/modules/dataset/routes.py
  app/modules/dataset/seeders.py
  app/modules/dataset/services.py
  app/modules/dataset/templates/dataset/list_datasets.html
  app/modules/dataset/tests/locustfile.py
  app/modules/dataset/tests/test_selenium.py
  app/modules/dataset/tests/test_unit.py
  app/modules/dataset/uvl_examples/file13.uvl
  app/modules/dataset/uvl_examples/file14.uvl
  app/modules/dataset/uvl_examples/file15.uvl
  app/modules/fakenodo/routes.py
  app/modules/profile/routes.py
  app/modules/profile/templates/profile/summary.html
  app/modules/pytest.ini
  migrations/versions/3931fcdc68c7_.py
Labels: enhancement
